../scripts/create_course_package.sh FSCI BIOL 1010U
../scripts/create_course_package.sh FSCI BIOL 1011U
../scripts/create_course_package.sh FSCI BIOL 1020U
../scripts/create_course_package.sh FSCI BIOL 1021U
../scripts/create_course_package.sh FSCI BIOL 2010U
../scripts/create_course_package.sh FSCI BIOL 2020U
../scripts/create_course_package.sh FSCI BIOL 2030U
../scripts/create_course_package.sh FSCI BIOL 2050U
../scripts/create_course_package.sh FSCI BIOL 2060U
../scripts/create_course_package.sh FSCI BIOL 2080U
../scripts/create_course_package.sh FSCI BIOL 3010U
../scripts/create_course_package.sh FSCI BIOL 3020U
../scripts/create_course_package.sh FSCI BIOL 3031U
../scripts/create_course_package.sh FSCI BIOL 3032U
../scripts/create_course_package.sh FSCI BIOL 3040U
../scripts/create_course_package.sh FSCI BIOL 3051U
../scripts/create_course_package.sh FSCI BIOL 3060U
../scripts/create_course_package.sh FSCI BIOL 3080U
../scripts/create_course_package.sh FSCI BIOL 3620U
../scripts/create_course_package.sh FSCI BIOL 3650U
../scripts/create_course_package.sh FSCI BIOL 4010U
../scripts/create_course_package.sh FSCI BIOL 4020U
../scripts/create_course_package.sh FSCI BIOL 4030U
../scripts/create_course_package.sh FSCI BIOL 4040U
../scripts/create_course_package.sh FSCI BIOL 4050U
../scripts/create_course_package.sh FSCI BIOL 4060U
../scripts/create_course_package.sh FSCI BIOL 4070U
../scripts/create_course_package.sh FSCI BIOL 4080U
../scripts/create_course_package.sh FSCI BIOL 4410U
../scripts/create_course_package.sh FSCI BIOL 4420U
../scripts/create_course_package.sh FSCI BIOL 4430U
../scripts/create_course_package.sh FSCI CHEM 1010U
../scripts/create_course_package.sh FSCI CHEM 1020U
../scripts/create_course_package.sh FSCI CHEM 2010U
../scripts/create_course_package.sh FSCI CHEM 2020U
../scripts/create_course_package.sh FSCI CHEM 2030U
../scripts/create_course_package.sh FSCI CHEM 2040U
../scripts/create_course_package.sh FSCI CHEM 2120U
../scripts/create_course_package.sh FSCI CHEM 2130U
../scripts/create_course_package.sh FSCI CHEM 3040U
../scripts/create_course_package.sh FSCI CHEM 3120U
../scripts/create_course_package.sh FSCI CHEM 3140U
../scripts/create_course_package.sh FSCI CHEM 3220U
../scripts/create_course_package.sh FSCI CHEM 3510U
../scripts/create_course_package.sh FSCI CHEM 3520U
../scripts/create_course_package.sh FSCI CHEM 3530U
../scripts/create_course_package.sh FSCI CHEM 3540U
../scripts/create_course_package.sh FSCI CHEM 3830U
../scripts/create_course_package.sh FSCI CHEM 4010U
../scripts/create_course_package.sh FSCI CHEM 4040U
../scripts/create_course_package.sh FSCI CHEM 4050U
../scripts/create_course_package.sh FSCI CHEM 4060U
../scripts/create_course_package.sh FSCI CHEM 4080U
../scripts/create_course_package.sh FSCI CHEM 4110U
../scripts/create_course_package.sh FSCI CHEM 4120U
../scripts/create_course_package.sh FSCI CHEM 4410U
../scripts/create_course_package.sh FSCI CHEM 4420U
../scripts/create_course_package.sh FSCI CHEM 4430U
../scripts/create_course_package.sh FSCI CHEM 4510U
../scripts/create_course_package.sh FSCI CHEM 4520U
../scripts/create_course_package.sh FSCI CSCI 1030U
../scripts/create_course_package.sh FSCI CSCI 1040U
../scripts/create_course_package.sh FSCI CSCI 1060U
../scripts/create_course_package.sh FSCI CSCI 1061U
../scripts/create_course_package.sh FSCI CSCI 2000U
../scripts/create_course_package.sh FSCI CSCI 2010U
../scripts/create_course_package.sh FSCI CSCI 2020U
../scripts/create_course_package.sh FSCI CSCI 2040U
../scripts/create_course_package.sh FSCI CSCI 2050U
../scripts/create_course_package.sh FSCI CSCI 2072U
../scripts/create_course_package.sh FSCI CSCI 2110U
../scripts/create_course_package.sh FSCI CSCI 2160U
../scripts/create_course_package.sh FSCI CSCI 3010U
../scripts/create_course_package.sh FSCI CSCI 3020U
../scripts/create_course_package.sh FSCI CSCI 3030U
../scripts/create_course_package.sh FSCI CSCI 3055U
../scripts/create_course_package.sh FSCI CSCI 3060U
../scripts/create_course_package.sh FSCI CSCI 3070U
../scripts/create_course_package.sh FSCI CSCI 3090U
../scripts/create_course_package.sh FSCI CSCI 3150U
../scripts/create_course_package.sh FSCI CSCI 3230U
../scripts/create_course_package.sh FSCI CSCI 4020U
../scripts/create_course_package.sh FSCI CSCI 4040U
../scripts/create_course_package.sh FSCI CSCI 4100U
../scripts/create_course_package.sh FSCI CSCI 4110U
../scripts/create_course_package.sh FSCI CSCI 4120U
../scripts/create_course_package.sh FSCI CSCI 4130U
../scripts/create_course_package.sh FSCI CSCI 4160U
../scripts/create_course_package.sh FSCI CSCI 4410U
../scripts/create_course_package.sh FSCI CSCI 4420U
../scripts/create_course_package.sh FSCI CSCI 4430U
../scripts/create_course_package.sh FSCI FSCI 1010U
../scripts/create_course_package.sh FSCI FSCI 2010U
../scripts/create_course_package.sh FSCI FSCI 3010U
../scripts/create_course_package.sh FSCI FSCI 3030U
../scripts/create_course_package.sh FSCI FSCI 3040U
../scripts/create_course_package.sh FSCI FSCI 3110U
../scripts/create_course_package.sh FSCI FSCI 3120U
../scripts/create_course_package.sh FSCI FSCI 3210U
../scripts/create_course_package.sh FSCI FSCI 4020U
../scripts/create_course_package.sh FSCI FSCI 4030U
../scripts/create_course_package.sh FSCI FSCI 4050U
../scripts/create_course_package.sh FSCI FSCI 4410U
../scripts/create_course_package.sh FSCI FSCI 4420U
../scripts/create_course_package.sh FSCI FSCI 4430U
../scripts/create_course_package.sh FSCI MATH 1000U
../scripts/create_course_package.sh FSCI MATH 1010U
../scripts/create_course_package.sh FSCI MATH 1020U
../scripts/create_course_package.sh FSCI MATH 1850U
../scripts/create_course_package.sh FSCI MATH 2015U
../scripts/create_course_package.sh FSCI MATH 2050U
../scripts/create_course_package.sh FSCI MATH 2055U
../scripts/create_course_package.sh FSCI MATH 2060U
../scripts/create_course_package.sh FSCI MATH 2072U
../scripts/create_course_package.sh FSCI MATH 2080U
../scripts/create_course_package.sh FSCI MATH 3020U
../scripts/create_course_package.sh FSCI MATH 3030U
../scripts/create_course_package.sh FSCI MATH 3040U
../scripts/create_course_package.sh FSCI MATH 3050U
../scripts/create_course_package.sh FSCI MATH 3060U
../scripts/create_course_package.sh FSCI MATH 3070U
../scripts/create_course_package.sh FSCI MATH 4010U
../scripts/create_course_package.sh FSCI MATH 4020U
../scripts/create_course_package.sh FSCI MATH 4030U
../scripts/create_course_package.sh FSCI MATH 4041U
../scripts/create_course_package.sh FSCI MATH 4042U
../scripts/create_course_package.sh FSCI MATH 4050U
../scripts/create_course_package.sh FSCI MATH 4060U
../scripts/create_course_package.sh FSCI MATH 4410U
../scripts/create_course_package.sh FSCI MATH 4420U
../scripts/create_course_package.sh FSCI MATH 4430U
../scripts/create_course_package.sh FSCI PHY 1010U
../scripts/create_course_package.sh FSCI PHY 1020U
../scripts/create_course_package.sh FSCI PHY 1030U
../scripts/create_course_package.sh FSCI PHY 1040U
../scripts/create_course_package.sh FSCI PHY 2010U
../scripts/create_course_package.sh FSCI PHY 2030U
../scripts/create_course_package.sh FSCI PHY 2040U
../scripts/create_course_package.sh FSCI PHY 2050U
../scripts/create_course_package.sh FSCI PHY 2060U
../scripts/create_course_package.sh FSCI PHY 2900U
../scripts/create_course_package.sh FSCI PHY 3010U
../scripts/create_course_package.sh FSCI PHY 3020U
../scripts/create_course_package.sh FSCI PHY 3030U
../scripts/create_course_package.sh FSCI PHY 3040U
../scripts/create_course_package.sh FSCI PHY 3050U
../scripts/create_course_package.sh FSCI PHY 3060U
../scripts/create_course_package.sh FSCI PHY 3080U
../scripts/create_course_package.sh FSCI PHY 3900U
../scripts/create_course_package.sh FSCI PHY 4010U
../scripts/create_course_package.sh FSCI PHY 4020U
../scripts/create_course_package.sh FSCI PHY 4030U
../scripts/create_course_package.sh FSCI PHY 4040U
../scripts/create_course_package.sh FSCI PHY 4050U
../scripts/create_course_package.sh FSCI PHY 4080U
../scripts/create_course_package.sh FSCI PHY 4100U
../scripts/create_course_package.sh FSCI PHY 4120U
../scripts/create_course_package.sh FSCI PHY 4410U
../scripts/create_course_package.sh FSCI PHY 4420U
../scripts/create_course_package.sh FSCI PHY 4430U
../scripts/create_course_package.sh FSCI PHY 4910U
../scripts/create_course_package.sh FSCI PHY 4920U
../scripts/create_course_package.sh FSCI PHY 1010U
../scripts/create_course_package.sh FSCI PHY 1020U
../scripts/create_course_package.sh FSCI PHY 1030U
../scripts/create_course_package.sh FSCI PHY 2010U
../scripts/create_course_package.sh FSCI PHY 2030U
../scripts/create_course_package.sh FSCI PHY 2900U
